@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.almostreliable.lazierae2.compat.crafttweaker;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
