@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.almostreliable.lazierae2.inventory;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
