@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.almostreliable.lazierae2.component;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
