@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.almostreliable.lazierae2.progression;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
